name: filesize
description: A package to get humanized file sizes. Translate raw file size into human readable strings.
author: synw <synwe@yahoo.com>
homepage: https://github.com/synw/filesize

version: 1.0.3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dev_dependencies:
  test: ^1.5.1
  test_coverage: ^0.2.3
  pedantic: ^1.6.0